imports:
    - { resource: ../PullCode/pull.yml }
    - { resource: ../PushCode/push.yml }
    - { resource: ../Collabs/collabs.yml }

services:
    grace.welcome:
        class: Grace\Endpoints\Welcome
    grace.pull_endpoint:
        class: Grace\Endpoints\Pull
        arguments:
            - @grace.pull_flow
    grace.pull_flow:
        class: Grace\PullCode\Flow
        arguments:
            - @grace.puller
            - @grace.differ
            - @grace.zipper
            - @grace.subscriber
            - @grace.mailer
            - @grace.container
            - %grace.from%
            - @swiftmailer.mailer
    grace.some_domain_event_subscriber:
        class: Grace\ExampleSubscriber
        tags:
            -
                name: Grace\Dispatchers::READ_SUBSCRIBER
