imports:
    - { resource: ../PullCode/pull.yml }
    - { resource: ../PushCode/push.yml }
    - { resource: ../Collabs/collabs.yml }

services:
    grace.pull_flow:
        class: Grace\PullCode\Flow
    grace.pull_endpoint:
        class: Grace\Endpoints\Pull
        arguments:
            - @grace.pull_flow
    grace.push_flow:
        class: Grace\PushCode\Flow
    grace.push_endpoint:
        class: Grace\Endpoints\Push
        arguments:
            - @grace.push_flow
