#blocks:
#    - Bldr\Block\Gush\GushBlock

#gush:
#    some_setting: some_value

bldr:
    name: cordoval/matthew-7-12
    description: Matthew 7:12 project
    profiles:
        travisBeforeScript:
            description: Travis Profile for running server:run
            tasks:
                - prepare
                - lint
                - phpcs
        travisScript:
            description: Travis Profile to run test suite
            tasks:
                - test
        tdd:
            description: Local Development Profile
            tasks:
                - testLocal
                - watch
        docker:
            description: Docker setup
            tasks:
                - bootstrap
        cs:
            description: fix cs for once
            tasks:
                - runFixer
    tasks:
        bootstrap:
            calls:
                -
                    type: exec
                    failOnError: true
                    executable: composer
                    arguments: [-q, install, --prefer-dist]
                -
                    type: exec
                    failOnError: true
                    executable: cp
                    arguments: [app/config/parameters.yml.docker, app/config/parameters.yml]
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments: [console, doctrine:schema:update, --force, --env=dev]
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments: [console, doctrine:mongodb:schema:update, --env=dev]
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments: [console, cache:clear, --env=dev]
        prepare:
            calls:
                -
                    type: exec
                    failOnError: true
                    executable: cp
                    arguments: [app/config/parameters.yml.travis, app/config/parameters.yml]
                -
                    type: exec
                    failOnError: true
                    executable: composer
                    arguments: [-q, install, --prefer-dist]
                -
                    type: exec
                    executable: php
                    arguments: [console, doctrine:database:create, --env=test]
                -
                    type: exec
                    executable: php
                    arguments: [console, doctrine:schema:create, --env=test]
                -
                    type: exec
                    executable: php
                    arguments: [console, doctrine:schema:update, --force, --env=test]
                -
                    type: exec
                    executable: php
                    arguments: [console, doctrine:mongodb:schema:update, --env=test]
                -
                    type: exec
                    executable: php
                    arguments: [console, cache:clear, --env=test]
        lint:
            description: Lints the files of the project
            calls:
                -
                    type: apply
                    failOnError: true
                    src:
                        - { path: [src], files: *.php, recursive: true }
                    output: /dev/null
                    executable: php
                    arguments: [-l]
        phpcs:
            description: Runs the PHP Code Sniffer
            calls:
                -
                    type: exec
                    executable: php
                    arguments:
                        - bin/phpcs
                        - --standard=PSR2
                        - --report=full
                        - src/
                -
                    type: exec
                    output: /dev/null
                    append: false
                    executable: php
                    arguments:
                        - bin/phpcs
                        - --standard=PSR2
                        - --report=checkstyle
                        - --report-file=build/logs/checkstyle.xml
                        - src/
        test:
            description: Runs the PHPUnit Tests
            calls:
                -
                    type: background
                    failOnEror: false
                    executable: ./dev_built_in_server
                    arguments: []
                -
                    type: exec
                    failOnError: true
                    executable: php
                    arguments:
                        - deps/bin/phpunit
                        #- --exclude-group=travis
                        #- --coverage-text=php://stdout
        testLocal:
            description: Runs the PHPUnit Tests
            calls:
                -
                    type: exec
                    executable: clear
                -
                    type: exec
                    executable: php
                    arguments:
                        - deps/bin/phpunit
                        - --stop-on-failure
                        #- --group=now
        watch:
            description: Watch Task for Local Development
            calls:
                -
                    type: watch
                    src:
                        - { path: [src], files: *.php, recursive: true }
                    task: testLocal
        runFixer:
            description: Installs if not already and runs php-cs-fixer with custom .php_cs
            calls:
                -
                    type: exec
                    executable: curl
                    arguments:
                        - http://cs.sensiolabs.org/get/php-cs-fixer.phar
                        - -S
                        - -o
                        - php-cs-fixer.phar
                -
                    type: exec
                    executable: php
                    arguments:
                        - php-cs-fixer.phar
                        - fix
                        - .
