imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assets.yml }
    - { resource: mailer.yml }
    - { resource: persistence.yml }
    - { resource: templating.yml }
    - { resource: ../../src/Resources/services.yml }
    - { resource: implementation_detail.yml }
