bldr:
    profiles:
        beforeScript:
            description: Profile for running server:run
            tasks:
                - prepare
                - lint
        afterScript:
            description: Profile to run test suite
            tasks:
                - test
        tdd:
            description: Local Development Profile
            tasks:
                - testLocal
                - watch
        cs:
            description: fix cs for once
            tasks:
                - runFixer
        merge:
            description: merge flow for matthew
            tasks:
                - gushMerge
        rebase:
            description: rebase flow for matthew
            tasks:
                - gushRebase
        send:
            description: send email from pool
            tasks:
                - sendMail
