imports:
    - { resource: PullCode/pull.yml }
    - { resource: PushCode/push.yml }

services:
    grace.zipper:
        class: Grace\Collabs\Zipper
    grace.container:
        class: Grace\Domain\Container
